
services:

  minio:
    image: minio/minio:latest
    container_name: storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - warehouse:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - dqsdatalabs


  miniosetup:
    image: minio/mc:latest
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 2;
        /usr/bin/mc config host add warehouse http://minio:9000 minio minio123;
        /usr/bin/mc mb warehouse/flink;
        /usr/bin/mc mb warehouse/flink/checkpoints;
        /usr/bin/mc mb warehouse/flink/savepoints;
        exit 0
      "
    networks:
      - dqsdatalabs

  spark:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8286:8080
      - 8277:7077
    networks:
      - dqsdatalabs

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - dqsdatalabs


  jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    depends_on:
      - miniosetup
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - dqsdatalabs


  taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    scale: 1
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 2048m
        taskmanager.memory.network.fraction: 0.4
        taskmanager.memory.network.min: 512mb
        taskmanager.memory.network.max: 2gb
    networks:
      - dqsdatalabs


  jupyter:
    # build: 
    #   context: ./docker/jupyter
    #   dockerfile: Dockerfile
    image: dqsdatalabs-jupyter:latest
    container_name: notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./datasets:/home/jovyan/datasets
    depends_on:
      - taskmanager
      - minio
    command: "start-notebook.sh --NotebookApp.token="
    networks:
      - dqsdatalabs


networks:
  dqsdatalabs:
    driver: bridge
    ipam:
      config:
        - subnet: "172.50.0.0/24"
          gateway: "172.50.0.1"


volumes:
  warehouse:
    name: warehouse
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage/warehouse


  # kafka:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ./data/docker/labs/kafka

  # postgresql:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ./data/docker/labs/postgresql



      